#!/bin/bash
# \author Zachary Wartell, ...
# \copyright Zachary Wartell.  All rights reserved. 2020.
# \brief See $USAGE
#
# https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols

WELCOME_REPO=https://cci-git.uncc.edu/zwartell/welcome.git
SERVER=cci-git.uncc.edu

U="git-tutorial-troubleshooter [UNCC_USER_ID]\n"
U+="\n"
U+="- UNCC_USER_ID : your UNCC user id (without the @uncc.edu) that is also used in URL of your repo on $SERVER\n"
U+="\n"
U+="This script creates a directory 'git-tutorial-troubleshooter-XXX' and attempts to git clone the repo,\n"
U+="$WELCOME_REPO, from the server, $SERVER.\n"
U+="It attempts to use all common methods of remote access protocols to clone the repo.\n" 
U+="If a particular method fails, it reruns it a second time with verbose error tracing.\n"
U+="The output is also saved to a file log.txt in the newly created directory with prefix git-tutorial-troubleshooter.\n"
U+="The additional debugging info may be helpful to you, but it is primarily meant to be shared with the class TAs.\n" 

USAGE=$U

if [[ $# -eq 0 ]]
then 
	echo -e $USAGE
	exit 1
fi

USER_ID=$1

DIR=`pwd`
TEST_DIR=$(mktemp -d "$DIR"/git-tutorial-troubleshooter-XXX)
#rm -rf $TEST_DIR 
#mkdir $TEST_DIR 

pushd "$TEST_DIR" > /dev/null

# log outout to file and also display output on commandline
rm -f log.txt
tail -f log.txt &
exec > log.txt 2>&1

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

echo -e "${red}"
echo -e "${red} --- Testing remotely git clone '$WELCOME_REPO'"
echo ---
echo -e "${reset}"

echo "- Attempting Git clone with HTTPS while bypassing any installed Credential Manager"
echo "-    Note: By default this will prompt you for your UNCC SSO userid and password"
echo "-          If you installed a Personal Access Token on $SERVER, git will expect your UNCC SSO userid and your PAT"
rm -rf welcome-https
git clone --config credential.helper= https://cci-git.uncc.edu/zwartell/welcome.git welcome-https
GIT_CRED_MANG=$?
if [[ $GIT_CRED_MANG -ne 0 ]]
then
	echo -   retrying while recording verbose debugging output
	git clone --config credential.helper= --verbose https://cci-git.uncc.edu/zwartell/welcome.git welcome-https
else
	echo
	echo "   SUCCESS!"
	echo
fi

echo 
echo 

# assume ssh keys were installed 
echo '--- Attempting Git clone with SSH'
echo '-       Note: This will only be successful if you have properly setup your SSH git protocol.'
rm -rf welcome-ssh
git clone git@cci-git.uncc.edu:zwartell/welcome.git welcome-ssh
GIT_SSH=$?
if [[ $GIT_SSH -ne 0 ]]
then
	echo
	echo "-   retrying while recording verbose debugging output"
	echo - 
	#echo 'ssh -vvv "$*"' > ssh && chmod +x ssh
	ssh -vvvT git clone --verbose git@cci-git.uncc.edu:zwartell/welcome.git welcome-ssh
	rm -f ssh
else
	echo
	echo "   SUCCESS!"
	echo
fi

echo 
echo 
# assume no credential manager is installed and using Personal Access Tokens
rm -rf welcome-pat
echo '--- Attempting Git clone with Personal Access Token'
echo '-       Note: This will only be successful if you have properly setup your PAT' 
echo -
read -p '-  Enter your Personal Access Token: ' PAT ;
git clone https://$USER_ID:$PAT@cci-git.uncc.edu/zwartell/welcome.git welcome-pat
GIT_PAT=$?
if [[ $GIT_PAT -ne 0 ]]
then
	echo -   retrying while recording verbose debugging output
	echo - 
	git clone --verbose https://$USER_ID:$PAT@cci-git.uncc.edu/zwartell/welcome.git welcome-https
else
	echo
	echo "   SUCCESS!"
	echo
fi

echo 
echo 
#find . -maxdepth 2

popd > /dev/null
