#!/bin/bash
# @author Zachary Wartell
# @brief

# replace the string $REVISION$ with the git log's date of last revision in the file index.html
#sed -i -e s/[$]REVISION[$]/"$(git log --format=format:\"%cD\" HEAD@{1}..HEAD)"/ .public/index.html
git show --no-patch --no-notes --pretty='%cd' > REVISION.txt
sed -i -e s/[$]REVISION[$]/"$(cat REVISION.txt)"/ "../Site Root/Git Tutorial.html"

rm ftp.cmd
echo cd 'public_html/Teaching/Git\ Tutorial'  > ftp.cmd
echo lcd '../Site\ Root'                      >> ftp.cmd
echo put -R . .                               >> ftp.cmd

sftp 'zwartell@webpages.uncc.edu' < ftp.cmd
