#!/bin/bash
# \author Zachary Wartell

PAT=$1
OUTFILE=$2

touch $OUTFILE

page=1
done=0
while [ $done -ne 1 ]
do
    #echo $page
    rm temp.json
    curl --header "PRIVATE-TOKEN: $PAT"  --ssl-revoke-best-effort --request GET "https://cci-git.charlotte.edu/api/v4/projects?per_page=100&page=$page" > temp.json
    if [ `cat temp.json | wc -c` -lt 2 ]
    then
        echo DONE
        cat temp.json
        done=1
    else
        cat temp.json >> $OUTFILE
        page=$(( page + 1 ))    
    fi
done   
